NOMES_DE_SINAIS = {
    0: 'Limite de velocidade (20km/h)',
    1: 'Limite de velocidade (30km/h)',
    2: 'Limite de velocidade (50km/h)',
    3: 'Limite de velocidade (60km/h)',
    4: 'Limite de velocidade (70km/h)',
    5: 'Limite de velocidade (80km/h)',
    6: 'Fim do limite de velocidade (80km/h)',
    7: 'Limite de velocidade (100km/h)',
    8: 'Limite de velocidade (120km/h)',
    9: 'Proibido ultrapassar',
    10: 'Proibido ultrapassar veículos com mais de 3,5 toneladas',
    11: 'Prioridade na próxima interseção',
    12: 'Estrada prioritária',
    13: 'Dê a preferência',
    14: 'Pare',
    15: 'Proibido veículos',
    16: 'Proibido veículos com mais de 3,5 toneladas',
    17: 'Entrada proibida',
    18: 'Cuidado geral',
    19: 'Curva perigosa à esquerda',
    20: 'Curva perigosa à direita',
    21: 'Curva dupla',
    22: 'Estrada irregular',
    23: 'Estrada escorregadia',
    24: 'Estreitamento da pista à direita',
    25: 'Obras na pista',
    26: 'Semáforos',
    27: 'Pedestres',
    28: 'Travessia de crianças',
    29: 'Travessia de bicicletas',
    30: 'Cuidado com gelo/neve',
    31: 'Travessia de animais selvagens',
    32: 'Fim de todos os limites de velocidade e ultrapassagem',
    33: 'Vire à direita à frente',
    34: 'Vire à esquerda à frente',
    35: 'Siga em frente',
    36: 'Siga em frente ou à direita',
    37: 'Siga em frente ou à esquerda',
    38: 'Mantenha-se à direita',
    39: 'Mantenha-se à esquerda',
    40: 'Rotatória obrigatória',
    41: 'Fim da proibição de ultrapassagem',
    42: 'Fim da proibição de ultrapassagem para veículos com mais de 3,5 toneladas'
}
